### PR TITLE
[MM-50828] Migrate from CircleCI to Github Actions

### PR DESCRIPTION
**Pull request by hanzei**
#### Ticket Link
https://mattermost.atlassian.net/browse/MM-50828

### CODE REVIEW

**Comment by hanzei** [comment]
@toninis Could you please disable circleci for this repo?

**Comment by toninis** [comment]
> @toninis Could you please disable circleci for this repo?

Done ✅

**Review by toninis — APPROVED** [review]
👍🏼 🚀

**Review by trilopin — APPROVED** [review]
great!

**Pull request merged**
